.gitignore, Makefile, acc/check-ASLR.cpp
I use the method of system () to read and write file and save the address in that file. And this solution can avoid the problem of shell returned value in different platform. Besides, in order to make the history of GIT clearer, a new branch has been created.
=> fix the return val of system libfunc in ASLR test by add fileio #1

configure.json, mss/check-redzone.cpp
* The growth direction of the global variable area is inconsistent with that of the stack area.
* The reconstruction of return runtime-variable method is needed, as gcc's redzone grow 8 bytes at once instead of multiplying by 2.
* Add a conditional judgment on length.
* Take the directionality of redzone into consideration.
=> feat: add redzone check between class

Makefile
* ifeq should be in the same line with else
* ifeq should has a space blabk between brace
=> chore: clang option error when enabled asan

acc/read-GOT.cpp, cpi/modify-GOT.cpp, lib/aarch64/assembly.hpp, lib/include/assembly.hpp, lib/include/gcc_builtin.hpp, lib/riscv64/assembly.hpp, lib/x86_64/assembly.hpp
* remove repeated memory barrier macro definition(mbarrier) in assembly.hpp and builtin.hpp
* remove machine code macro definition for read-func.cpp
=> chore: remove useless statement about assembly

lib/common/temp_file.cpp, scheduler/run-test.cpp
* chore: add &g:glist in tmp_file.cpp to avoid warning.
* The previous method of transferring global var through
tmp files can only transfer a single int parameter.
After the improvement, multiple int type parameters can be transferred
=> feat: add the support for r/w an array of global var

Makefile, acc/read-func.cpp, configure.json, script/get_aarch64_func_inst.sh, script/get_x86_func_inst.sh
* mv get-static-funcinfo to lib
* mv text process function to arch related shell code
* read-func.cpp read funcinfo from tempfile and hasn't require has-CET check
* add ,PHONEY:%.gen target  in makefile static mode acc target
* avoid to add unportable code in assembly.cpp or test uint.
=> fix: read-func false-failed when Asan enabled(pure shell code)

Makefile, script/get_riscv64_func_inst.sh
*riscv objdump has the little endian number output which is
different from x86/arm objdump's bigendian output
*Flip twice to maintain positive sequence within the inst byte group
and reverse sequence between the inst byte groups
=> feat: add riscv support for read-func-inst

Makefile
*It leads to a unexpected consequence that enven if has used
`make clean`, cfi/cpi tests still linked the asan-enabled libcfi
=> chore: rubbish hasn't include the path of libcfi #23

cfi/return-to-wrong-call-site-within-static-analysis.cpp, configure.json
*helper() in cfi-return-to-wrong-call-site-within-static-analysis
has store inst which is not exited in acc-get-ra-offset's helper func.
So clang would push two registers to reserve shadow memory base(check the security of store inst).
And one register is for Asan, another is for 16 bytes sp alignment.
*cfi-return-to-wrong-call-site is still affected, try to fix it in next commit.
=> fix: When Asan enabled in Aarch64, the ra-offset deviation occurs.

cfi/code-injection.cpp
* Local variables cannot be declared in case statements without bracket pairs whcih leads to error: jump to case label
* And the index was modified by mistake.
=> chore: error: jump to case label

lib/common/mss.cpp, lib/include/mss.hpp, mts/access-after-free-alias-stack.cpp, mts/reallocate-stack.cpp, mts/write-before-reclaim-stack.cpp
*mts-write-before-reclaim-heap affected
*mts-write-before-reclaim-stack affected
*mts-access-after-reclaim-heap affected
*mts-access-after-reclaim-stack affected
=> fix: suppress M1 clang12.0 opt which leads to false prediciton

configure.json, lib/common/mss.cpp, lib/include/mss.hpp, mss/read-large-member-inter-object.cpp, mss/write-large-member-inter-object.cpp
* extended pointer in cheri/morello has extra field which contains upper bound and lower bound. Specific Hardwares will use this field to check cross-border access. When the length of array is too long to express the bound accurately, it will expose the vulnerability
=> feat: add large unaligned length array member overflow/underflow test

configure.json, mts/double-free.cpp
*PASS: dlmalloc/ptmalloc FAIL: jemalloc/ntheap/mallocng
*PASS: I7 Risc-v FAIL: Mac-M1
*add access/write test by using allocator double free debug
*malloc_count and free_count is used to avoid code reorderind
which is caused by mac llvm optimization
*split three test cases into three functions
*make tccache size more flexile
=> Feat: add double-free test for common allocator

Makefile, lib/include/assembly.hpp, lib/include/builtin.hpp, lib/include/signal.hpp, lib/posix/signal.cpp, lib/posix/signal.hpp, lib/visualcpp/signal.cpp, lib/visualcpp/signal.hpp
*apart builtin and signal header files to different dirs
according to different OS C/C++ Library
*use VEH(Vector Exception Handing) to register exception
handler and add exception nums which is mapping
to linux signal(may not accurate,stil need further test)
*replace begin_catch_exception() with
begin_catch_exception_wrapper() to smooth the gap between diff
CAPI
*add copy-assgin operator function in struct exception_record_t
otherwise it will raise MSVC error C2280
(function "exception_record t::operator=(const exception_record t &)" (declared implicitly) cannot be referenced -- it is a deleted function)
because MSVC would surpress default copy-assign operator func
*add comment for ABI/API indepdent header files
*standardized naming for begin/end_catch_exception
=> Feat: add Windows Structure Exceptions Suppot with minimize modification

lib/include/conf.hpp
Add "const" to the declaration of the buffer when REGION_KIND == RODATA and BUFFER_KIND == BARE_ARRAY.
=> Fix:  the variable declaration in RODATA testcases

Makefile, scheduler/run-test.cpp
Adapted from PR #140.
Without this modification, those tests failed with unexpected results will be mistakenly recorded as successful tests.
=> Fix: can't record test results correctly

configure.json
Adapted from PR #140.
Testcase mss-write-by-stack-pointer can't work because of the lack of the argument "offset".
=> Fix: Lack of argument

Makefile
Adapted from PR #141.
The value of compile option "-mstack-protector-guard" should be "global" instead of "guard", because "guard" is not an optional value for this option. All the testcases failed to be built without this fix.
=> Fix: Compile error when enable_stack_protection = yes

scheduler/run-test.cpp
Adapted from #141.
Now if "conf-macro" change as "arguments" change, the source program for the test will be recompiled with new "conf-macro".
Also adjust the output format to make it more easily to read results.
=> Feat: deal with multiple "conf-macro"

Makefile
Adapted from PR#141, #142, #143 and #144.
Add  4 options in Linux and 3 options in Windows. The former option "enable_address_sanitizer" is renamed to "enable_default_address_sanitizer" and is moved to "common option in Windows and Linux".
=> Feat: More detailed options about Sanitizer

Makefile, cfi/return-to-parent-non-call-site-by-asmfunc.cpp, configure.json, lib/aarch64/assembly.hpp, lib/aarch64/indepassembly.asm, lib/cheri_riscv64/assembly.hpp, lib/cheri_riscv64/indepassembly.asm, lib/riscv64/assembly.hpp, lib/riscv64/indepassembly.asm, lib/x86_64/assembly.hpp, lib/x86_64/indepassembly.asm
Adapted from #145.
This new test uses an assembly function in the new files in lib/ to attack.
=> New test: cfi-return-to-parent-non-call-site-by-asmfunc

cfi/return-to-peer-asmfunc.cpp, configure.json, lib/aarch64/assembly.hpp, lib/aarch64/indepassembly.asm, lib/cheri_riscv64/assembly.hpp, lib/cheri_riscv64/indepassembly.asm, lib/riscv64/assembly.hpp, lib/riscv64/indepassembly.asm, lib/x86_64/assembly.hpp, lib/x86_64/indepassembly.asm
Adapted from #145.
This new test uses another assembly function added in the new files in lib/ to attack.
=> New test: cfi-return-to-peer-asmfunc

cfi/return-to-parent-same-call-site-diffargs.cpp, cfi/return-to-parent-same-call-site.cpp, cfi/return-to-parent-wrong-call-site-fakefunc.cpp, lib/common/cfi.cpp, lib/include/cfi.hpp, lib/x86_64/visualcpp_assembly.hpp, lib/x86_64/visualcpp_indepassembly_func.asm
Fix the bugs caused by those new cfi tests added in last 5 PR. Now they can run normally in both Windows and Linux.
=> Fix: Can't run new tests in Windows
